package uke.utils

/**
 * Created with IntelliJ IDEA.
 * User: elattanzio
 * Date: 04/09/12
 * Time: 12:12
 * To change this template use File | Settings | File Templates.
 */
class CountryUtils {
    static       ISO_3166_2_TO_ISO_3166_3 = [
        "ax": "ala",
        "af": "afg",
        "al": "alb",
        "dz": "dza",
        "as": "asm",
        "ad": "and",
        "ao": "ago",
        "ai": "aia",
        "aq": "ata",
        "ag": "atg",
        "ar": "arg",
        "am": "arm",
        "aw": "abw",
        "au": "aus",
        "at": "aut",
        "az": "aze",
        "bs": "bhs",
        "bh": "bhr",
        "bd": "bgd",
        "bb": "brb",
        "by": "blr",
        "be": "bel",
        "bz": "blz",
        "bj": "ben",
        "bm": "bmu",
        "bt": "btn",
        "bo": "bol",
        "ba": "bih",
        "bw": "bwa",
        "bv": "bvt",
        "br": "bra",
        "io": "iot",
        "bn": "brn",
        "bg": "bgr",
        "bf": "bfa",
        "bi": "bdi",
        "kh": "khm",
        "cm": "cmr",
        "ca": "can",
        "cv": "cpv",
        "ky": "cym",
        "cf": "caf",
        "td": "tcd",
        "cl": "chl",
        "cn": "chn",
        "cx": "cxr",
        "cc": "cck",
        "co": "col",
        "km": "com",
        "cd": "cod",
        "cg": "cog",
        "ck": "cok",
        "cr": "cri",
        "ci": "civ",
        "hr": "hrv",
        "cu": "cub",
        "cy": "cyp",
        "cz": "cze",
        "dk": "dnk",
        "dj": "dji",
        "dm": "dma",
        "do": "dom",
        "ec": "ecu",
        "eg": "egy",
        "sv": "slv",
        "gq": "gnq",
        "er": "eri",
        "ee": "est",
        "et": "eth",
        "fk": "flk",
        "fo": "fro",
        "fj": "fji",
        "fi": "fin",
        "fr": "fra",
        "gf": "guf",
        "pf": "pyf",
        "tf": "atf",
        "ga": "gab",
        "gm": "gmb",
        "ge": "geo",
        "de": "deu",
        "gh": "gha",
        "gi": "gib",
        "gr": "grc",
        "gl": "grl",
        "gd": "grd",
        "gp": "glp",
        "gu": "gum",
        "gt": "gtm",
        "gn": "gin",
        "gw": "gnb",
        "gy": "guy",
        "ht": "hti",
        "hm": "hmd",
        "hn": "hnd",
        "hk": "hkg",
        "hu": "hun",
        "is": "isl",
        "in": "ind",
        "id": "idn",
        "ir": "irn",
        "iq": "irq",
        "ie": "irl",
        "il": "isr",
        "it": "ita",
        "jm": "jam",
        "jp": "jpn",
        "jo": "jor",
        "kz": "kaz",
        "ke": "ken",
        "ki": "kir",
        "kp": "prk",
        "kr": "kor",
        "kw": "kwt",
        "kg": "kgz",
        "la": "lao",
        "lv": "lva",
        "lb": "lbn",
        "ls": "lso",
        "lr": "lbr",
        "ly": "lby",
        "li": "lie",
        "lt": "ltu",
        "lu": "lux",
        "mo": "mac",
        "mk": "mkd",
        "mg": "mdg",
        "mw": "mwi",
        "my": "mys",
        "mv": "mdv",
        "ml": "mli",
        "mt": "mlt",
        "mh": "mhl",
        "mq": "mtq",
        "mr": "mrt",
        "mu": "mus",
        "yt": "myt",
        "mx": "mex",
        "fm": "fsm",
        "md": "mda",
        "mc": "mco",
        "mn": "mng",
        "ms": "msr",
        "ma": "mar",
        "mz": "moz",
        "mm": "mmr",
        "na": "nam",
        "nr": "nru",
        "np": "npl",
        "nl": "nld",
        "an": "ant",
        "nc": "ncl",
        "nz": "nzl",
        "ni": "nic",
        "ne": "ner",
        "ng": "nga",
        "nu": "niu",
        "nf": "nfk",
        "mp": "mnp",
        "no": "nor",
        "om": "omn",
        "pk": "pak",
        "pw": "plw",
        "ps": "pse",
        "pa": "pan",
        "pg": "png",
        "py": "pry",
        "pe": "per",
        "ph": "phl",
        "pn": "pcn",
        "pl": "pol",
        "pt": "prt",
        "pr": "pri",
        "qa": "qat",
        "re": "reu",
        "ro": "rou",
        "ru": "rus",
        "rw": "rwa",
        "sh": "shn",
        "kn": "kna",
        "lc": "lca",
        "pm": "spm",
        "vc": "vct",
        "ws": "wsm",
        "sm": "smr",
        "st": "stp",
        "sa": "sau",
        "sn": "sen",
        "cs": "scg",
        "sc": "syc",
        "sl": "sle",
        "sg": "sgp",
        "sk": "svk",
        "si": "svn",
        "sb": "slb",
        "so": "som",
        "za": "zaf",
        "gs": "sgs",
        "es": "esp",
        "lk": "lka",
        "sd": "sdn",
        "sr": "sur",
        "sj": "sjm",
        "sz": "swz",
        "se": "swe",
        "ch": "che",
        "sy": "syr",
        "tw": "twn",
        "tj": "tjk",
        "tz": "tza",
        "th": "tha",
        "tl": "tls",
        "tg": "tgo",
        "tk": "tkl",
        "to": "ton",
        "tt": "tto",
        "tn": "tun",
        "tr": "tur",
        "tm": "tkm",
        "tc": "tca",
        "tv": "tuv",
        "ug": "uga",
        "ua": "ukr",
        "ae": "are",
        "gb": "gbr",
        "us": "usa",
        "um": "umi",
        "uy": "ury",
        "uz": "uzb",
        "vu": "vut",
        "va": "vat",
        "ve": "ven",
        "vn": "vnm",
        "vg": "vgb",
        "vi": "vir",
        "wf": "wlf",
        "eh": "esh",
        "ye": "yem",
        "zm": "zmb",
        "zw": "zwe"
    ]
    static       ISO_3166_3_TO_ISO_3166_2 = [
        "ala": "ax",
        "afg": "af",
        "alb": "al",
        "dza": "dz",
        "asm": "as",
        "and": "ad",
        "ago": "ao",
        "aia": "ai",
        "ata": "aq",
        "atg": "ag",
        "arg": "ar",
        "arm": "am",
        "abw": "aw",
        "aus": "au",
        "aut": "at",
        "aze": "az",
        "bhs": "bs",
        "bhr": "bh",
        "bgd": "bd",
        "brb": "bb",
        "blr": "by",
        "bel": "be",
        "blz": "bz",
        "ben": "bj",
        "bmu": "bm",
        "btn": "bt",
        "bol": "bo",
        "bih": "ba",
        "bwa": "bw",
        "bvt": "bv",
        "bra": "br",
        "iot": "io",
        "brn": "bn",
        "bgr": "bg",
        "bfa": "bf",
        "bdi": "bi",
        "khm": "kh",
        "cmr": "cm",
        "can": "ca",
        "cpv": "cv",
        "cym": "ky",
        "caf": "cf",
        "tcd": "td",
        "chl": "cl",
        "chn": "cn",
        "cxr": "cx",
        "cck": "cc",
        "col": "co",
        "com": "km",
        "cod": "cd",
        "cog": "cg",
        "cok": "ck",
        "cri": "cr",
        "civ": "ci",
        "hrv": "hr",
        "cub": "cu",
        "cyp": "cy",
        "cze": "cz",
        "dnk": "dk",
        "dji": "dj",
        "dma": "dm",
        "dom": "do",
        "ecu": "ec",
        "egy": "eg",
        "slv": "sv",
        "gnq": "gq",
        "eri": "er",
        "est": "ee",
        "eth": "et",
        "flk": "fk",
        "fro": "fo",
        "fji": "fj",
        "fin": "fi",
        "fra": "fr",
        "guf": "gf",
        "pyf": "pf",
        "atf": "tf",
        "gab": "ga",
        "gmb": "gm",
        "geo": "ge",
        "deu": "de",
        "gha": "gh",
        "gib": "gi",
        "grc": "gr",
        "grl": "gl",
        "grd": "gd",
        "glp": "gp",
        "gum": "gu",
        "gtm": "gt",
        "gin": "gn",
        "gnb": "gw",
        "guy": "gy",
        "hti": "ht",
        "hmd": "hm",
        "hnd": "hn",
        "hkg": "hk",
        "hun": "hu",
        "isl": "is",
        "ind": "in",
        "idn": "id",
        "irn": "ir",
        "irq": "iq",
        "irl": "ie",
        "isr": "il",
        "ita": "it",
        "jam": "jm",
        "jpn": "jp",
        "jor": "jo",
        "kaz": "kz",
        "ken": "ke",
        "kir": "ki",
        "prk": "kp",
        "kor": "kr",
        "kwt": "kw",
        "kgz": "kg",
        "lao": "la",
        "lva": "lv",
        "lbn": "lb",
        "lso": "ls",
        "lbr": "lr",
        "lby": "ly",
        "lie": "li",
        "ltu": "lt",
        "lux": "lu",
        "mac": "mo",
        "mkd": "mk",
        "mdg": "mg",
        "mwi": "mw",
        "mys": "my",
        "mdv": "mv",
        "mli": "ml",
        "mlt": "mt",
        "mhl": "mh",
        "mtq": "mq",
        "mrt": "mr",
        "mus": "mu",
        "myt": "yt",
        "mex": "mx",
        "fsm": "fm",
        "mda": "md",
        "mco": "mc",
        "mng": "mn",
        "msr": "ms",
        "mar": "ma",
        "moz": "mz",
        "mmr": "mm",
        "nam": "na",
        "nru": "nr",
        "npl": "np",
        "nld": "nl",
        "ant": "an",
        "ncl": "nc",
        "nzl": "nz",
        "nic": "ni",
        "ner": "ne",
        "nga": "ng",
        "niu": "nu",
        "nfk": "nf",
        "mnp": "mp",
        "nor": "no",
        "omn": "om",
        "pak": "pk",
        "plw": "pw",
        "pse": "ps",
        "pan": "pa",
        "png": "pg",
        "pry": "py",
        "per": "pe",
        "phl": "ph",
        "pcn": "pn",
        "pol": "pl",
        "prt": "pt",
        "pri": "pr",
        "qat": "qa",
        "reu": "re",
        "rou": "ro",
        "rus": "ru",
        "rwa": "rw",
        "shn": "sh",
        "kna": "kn",
        "lca": "lc",
        "spm": "pm",
        "vct": "vc",
        "wsm": "ws",
        "smr": "sm",
        "stp": "st",
        "sau": "sa",
        "sen": "sn",
        "scg": "cs",
        "syc": "sc",
        "sle": "sl",
        "sgp": "sg",
        "svk": "sk",
        "svn": "si",
        "slb": "sb",
        "som": "so",
        "zaf": "za",
        "sgs": "gs",
        "esp": "es",
        "lka": "lk",
        "sdn": "sd",
        "sur": "sr",
        "sjm": "sj",
        "swz": "sz",
        "swe": "se",
        "che": "ch",
        "syr": "sy",
        "twn": "tw",
        "tjk": "tj",
        "tza": "tz",
        "tha": "th",
        "tls": "tl",
        "tgo": "tg",
        "tkl": "tk",
        "ton": "to",
        "tto": "tt",
        "tun": "tn",
        "tur": "tr",
        "tkm": "tm",
        "tca": "tc",
        "tuv": "tv",
        "uga": "ug",
        "ukr": "ua",
        "are": "ae",
        "gbr": "gb",
        "usa": "us",
        "umi": "um",
        "ury": "uy",
        "uzb": "uz",
        "vut": "vu",
        "vat": "va",
        "ven": "ve",
        "vnm": "vn",
        "vgb": "vg",
        "vir": "vi",
        "wlf": "wf",
        "esh": "eh",
        "yem": "ye",
        "zmb": "zm",
        "zwe": "zw"
    ]
    static final ISO3166_3                = [
        "afg": "Afghanistan",
        "alb": "Albania",
        "ata": "Antarctica",
        "dza": "Algeria",
        "asm": "American Samoa",
        "and": "Andorra",
        "ago": "Angola",
        "atg": "Antigua and Barbuda",
        "aze": "Azerbaijan",
        "arg": "Argentina",
        "aus": "Australia",
        "aut": "Austria",
        "bhs": "Bahamas",
        "bhr": "Bahrain",
        "bgd": "Bangladesh",
        "arm": "Armenia",
        "brb": "Barbados",
        "bel": "Belgium",
        "bmu": "Bermuda",
        "btn": "Bhutan",
        "bol": "Bolivia",
        "bih": "Bosnia and Herzegovina",
        "bwa": "Botswana",
        "bvt": "Bouvet Island",
        "bra": "Brazil",
        "blz": "Belize",
        "iot": "British Indian Ocean Territory",
        "slb": "Solomon Islands",
        "vgb": "British Virgin Islands",
        "brn": "Brunei Darussalam",
        "bgr": "Bulgaria",
        "mmr": "Myanmar",
        "bdi": "Burundi",
        "blr": "Belarus",
        "khm": "Cambodia",
        "cmr": "Cameroon",
        "can": "Canada",
        "cpv": "Cape Verde",
        "cym": "Cayman Islands",
        "caf": "Central African",
        "lka": "Sri Lanka",
        "tcd": "Chad",
        "chl": "Chile",
        "chn": "China",
        "twn": "Taiwan",
        "cxr": "Christmas Island",
        "cck": "Cocos (Keeling) Islands",
        "col": "Colombia",
        "com": "Comoros",
        "myt": "Mayotte",
        "cog": "Republic of the Congo",
        "cod": "The Democratic Republic Of The Congo",
        "cok": "Cook Islands",
        "cri": "Costa Rica",
        "hrv": "Croatia",
        "cub": "Cuba",
        "cyp": "Cyprus",
        "cze": "Czech Republic",
        "ben": "Benin",
        "dnk": "Denmark",
        "dma": "Dominica",
        "dom": "Dominican Republic",
        "ecu": "Ecuador",
        "slv": "El Salvador",
        "gnq": "Equatorial Guinea",
        "eth": "Ethiopia",
        "eri": "Eritrea",
        "est": "Estonia",
        "fro": "Faroe Islands",
        "flk": "Falkland Islands",
        "sgs": "South Georgia and the South Sandwich Islands",
        "fji": "Fiji",
        "fin": "Finland",
        "ala": "\u00C5land Islands",
        "fra": "France",
        "guf": "French Guiana",
        "pyf": "French Polynesia",
        "atf": "French Southern Territories",
        "dji": "Djibouti",
        "gab": "Gabon",
        "geo": "Georgia",
        "gmb": "Gambia",
        "pse": "Occupied Palestinian Territory",
        "deu": "Germany",
        "gha": "Ghana",
        "gib": "Gibraltar",
        "kir": "Kiribati",
        "grc": "Greece",
        "grl": "Greenland",
        "grd": "Grenada",
        "glp": "Guadeloupe",
        "gum": "Guam",
        "gtm": "Guatemala",
        "gin": "Guinea",
        "guy": "Guyana",
        "hti": "Haiti",
        "hmd": "Heard Island and McDonald Islands",
        "vat": "Vatican City State",
        "hnd": "Honduras",
        "hkg": "Hong Kong",
        "hun": "Hungary",
        "isl": "Iceland",
        "ind": "India",
        "idn": "Indonesia",
        "irn": "Islamic Republic of Iran",
        "irq": "Iraq",
        "irl": "Ireland",
        "isr": "Israel",
        "ita": "Italy",
        "civ": "C\u00F4te d'Ivoire",
        "jam": "Jamaica",
        "jpn": "Japan",
        "kaz": "Kazakhstan",
        "jor": "Jordan",
        "ken": "Kenya",
        "prk": "Democratic People's Republic of Korea",
        "kor": "Republic of Korea",
        "kwt": "Kuwait",
        "kgz": "Kyrgyzstan",
        "lao": "Lao People's Democratic Republic",
        "lbn": "Lebanon",
        "lso": "Lesotho",
        "lva": "Latvia",
        "lbr": "Liberia",
        "lby": "Libyan Arab Jamahiriya",
        "lie": "Liechtenstein",
        "ltu": "Lithuania",
        "lux": "Luxembourg",
        "mac": "Macao",
        "mdg": "Madagascar",
        "mwi": "Malawi",
        "mys": "Malaysia",
        "mdv": "Maldives",
        "mli": "Mali",
        "mlt": "Malta",
        "mtq": "Martinique",
        "mrt": "Mauritania",
        "mus": "Mauritius",
        "mex": "Mexico",
        "mco": "Monaco",
        "mng": "Mongolia",
        "mda": "Republic of Moldova",
        "msr": "Montserrat",
        "mar": "Morocco",
        "moz": "Mozambique",
        "omn": "Oman",
        "nam": "Namibia",
        "nru": "Nauru",
        "npl": "Nepal",
        "nld": "Netherlands",
        "ant": "Netherlands Antilles",
        "abw": "Aruba",
        "ncl": "New Caledonia",
        "vut": "Vanuatu",
        "nzl": "New Zealand",
        "nic": "Nicaragua",
        "ner": "Niger",
        "nga": "Nigeria",
        "niu": "Niue",
        "nfk": "Norfolk Island",
        "nor": "Norway",
        "mnp": "Northern Mariana Islands",
        "umi": "United States Minor Outlying Islands",
        "fsm": "Federated States of Micronesia",
        "mhl": "Marshall Islands",
        "plw": "Palau",
        "pak": "Pakistan",
        "pan": "Panama",
        "png": "Papua New Guinea",
        "pry": "Paraguay",
        "per": "Peru",
        "phl": "Philippines",
        "pcn": "Pitcairn",
        "pol": "Poland",
        "prt": "Portugal",
        "gnb": "Guinea-Bissau",
        "tls": "Timor-Leste",
        "pri": "Puerto Rico",
        "qat": "Qatar",
        "reu": "R\u00E9union",
        "rou": "Romania",
        "rus": "Russian Federation",
        "rwa": "Rwanda",
        "shn": "Saint Helena",
        "kna": "Saint Kitts and Nevis",
        "aia": "Anguilla",
        "lca": "Saint Lucia",
        "spm": "Saint-Pierre and Miquelon",
        "vct": "Saint Vincent and the Grenadines",
        "smr": "San Marino",
        "stp": "Sao Tome and Principe",
        "sau": "Saudi Arabia",
        "sen": "Senegal",
        "syc": "Seychelles",
        "sle": "Sierra Leone",
        "sgp": "Singapore",
        "svk": "Slovakia",
        "vnm": "Vietnam",
        "svn": "Slovenia",
        "som": "Somalia",
        "zaf": "South Africa",
        "zwe": "Zimbabwe",
        "esp": "Spain",
        "esh": "Western Sahara",
        "sdn": "Sudan",
        "sur": "Suriname",
        "sjm": "Svalbard and Jan Mayen",
        "swz": "Swaziland",
        "swe": "Sweden",
        "che": "Switzerland",
        "syr": "Syrian Arab Republic",
        "tjk": "Tajikistan",
        "tha": "Thailand",
        "tgo": "Togo",
        "tkl": "Tokelau",
        "ton": "Tonga",
        "tto": "Trinidad and Tobago",
        "are": "United Arab Emirates",
        "tun": "Tunisia",
        "tur": "Turkey",
        "tkm": "Turkmenistan",
        "tca": "Turks and Caicos Islands",
        "tuv": "Tuvalu",
        "uga": "Uganda",
        "ukr": "Ukraine",
        "mkd": "The Former Yugoslav Republic of Macedonia",
        "egy": "Egypt",
        "gbr": "United Kingdom",
        "imn": "Isle of Man",
        "tza": "United Republic Of Tanzania",
        "usa": "United States",
        "vir": "U.S. Virgin Islands",
        "bfa": "Burkina Faso",
        "ury": "Uruguay",
        "uzb": "Uzbekistan",
        "ven": "Venezuela",
        "wlf": "Wallis and Futuna",
        "wsm": "Samoa",
        "yem": "Yemen",
        "scg": "Serbia and Montenegro",
        "zmb": "Zambia",
    ]


    static String getCountryCode3Letters(String key) {
        if (key.length() == 2)
            ISO_3166_2_TO_ISO_3166_3[key]
        else if (key.length() == 3 && ISO_3166_3_TO_ISO_3166_2.containsKey(key))
            key
    }

    static String getCountryName(String key) {
        if (key.length() == 2)
            key = ISO_3166_2_TO_ISO_3166_3[key]
        ISO3166_3[key]
    }
}
