wget http://www.admintasia.com/admintasia_v1/images/icons/Book_phones.png    
wget http://www.admintasia.com/admintasia_v1/images/icons/Books.png          
wget http://www.admintasia.com/admintasia_v1/images/icons/Box_content.png    
wget http://www.admintasia.com/admintasia_v1/images/icons/Box_recycle.png    
wget http://www.admintasia.com/admintasia_v1/images/icons/Briefcase_files.png
wget http://www.admintasia.com/admintasia_v1/images/icons/Chart_4.png        
wget http://www.admintasia.com/admintasia_v1/images/icons/Chart_5.png        
wget http://www.admintasia.com/admintasia_v1/images/icons/Clipboard_3.png    
wget http://www.admintasia.com/admintasia_v1/images/icons/Glass.png          
wget http://www.admintasia.com/admintasia_v1/images/icons/Globe.png          
wget http://www.admintasia.com/admintasia_v1/images/icons/Mail_compose.png   
wget http://www.admintasia.com/admintasia_v1/images/icons/Mail_open.png      
wget http://www.admintasia.com/admintasia_v1/images/icons/Monitor.png        
wget http://www.admintasia.com/admintasia_v1/images/icons/Star.png           
wget http://www.admintasia.com/admintasia_v1/images/icons/error.png          
wget http://www.admintasia.com/admintasia_v1/images/icons/info.png           
wget http://www.admintasia.com/admintasia_v1/images/icons/notice.png         
wget http://www.admintasia.com/admintasia_v1/images/icons/success.png        
